Check for unset git configs in init
Fixes #17 by checking in the main attache entry point.

Since most or all attache commands will rely on git being setup
correctly, it seems to make sense to have it there.

diff --git a/lib/attache b/lib/attache
--- a/lib/attache
+++ b/lib/attache
@@ -16,6 +16,21 @@ if [ -n "$ATTACHE_DEBUG" ]; then
   set -x
 fi
 
+# Make sure that git commands won't fail because user isn't configured
+if git config --global user.name > /dev/null &&
+   git config --global user.email > /dev/null
+then
+    :
+else
+    echo "Attache relies heavily on git for it's functionality."
+    echo
+    echo -e 'Please set your git name and email with:\n
+  git config --global user.name "Your Name"
+  git config --global user.email "you@example.com"'
+    echo
+    exit 1
+fi
+
 export READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
   echo "attache: cannot find readlink - are you missing GNU coreutils?" >&2
