Make attache init allow named profiles. Add weak error checking.

diff --git a/lib/attache-init b/lib/attache-init
--- a/lib/attache-init
+++ b/lib/attache-init
@@ -21,9 +21,17 @@
 # along with Attaché. If not, see <http://www.gnu.org/licenses/>.
 
 set -e
-[ -n "$ATTACHE_DEBUG" ] && set -x
+[ -n "${ATTACHE_DEBUG}" ] && set -x
 
-[ -d $ATTACHE_PROFILE ] && echo "The directory $ATTACHE_PROFILE already exists!
+if [ ! $# -le 1 ]
+then
+    echo "Error: attache: Too many arguments."
+    attache help init && exit 1
+fi
+
+[ -n "$1" ] && ATTACHE_PROFILE="${ATTACHE_ROOT}/profiles/${1}"
+
+[ -d $ATTACHE_PROFILE ] && echo "The directory ${ATTACHE_PROFILE} already exists!
 Maybe you should change your ATTACHE_PROFILE environment variable..." && exit 1
 
 mkdir -p $ATTACHE_PROFILE
@@ -37,4 +45,4 @@ git commit -m "Initial commit"
 
 popd >/dev/null 2>/dev/null
 
-echo "Congratulations! You now have a brand new attache located at $ATTACHE_PROFILE"
+echo "Congratulations! You now have a brand new attache located at ${ATTACHE_PROFILE}."
